// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSync.Infrastructure.Data;

#nullable disable

namespace SkillSync.Infrastructure.Migrations
{
    [DbContext(typeof(SkillSyncDbContext))]
    [Migration("20251121190611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillSync.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Habilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.HabilidadeProfissional", b =>
                {
                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfissionalId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("HabilidadeProfissionais");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.HabilidadeVaga", b =>
                {
                    b.Property<Guid>("VagaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VagaId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("HabilidadeVagas");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModalidadeTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.RecomendacaoCarreira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("RecomendacaoCarreiras");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.TendenciaMercado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TendenciaMercados");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Vaga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.HabilidadeProfissional", b =>
                {
                    b.HasOne("SkillSync.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany("Profissionais")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSync.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Habilidades")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.HabilidadeVaga", b =>
                {
                    b.HasOne("SkillSync.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany("Vagas")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSync.Domain.Entities.Vaga", "Vaga")
                        .WithMany("Habilidades")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.RecomendacaoCarreira", b =>
                {
                    b.HasOne("SkillSync.Domain.Entities.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("SkillSync.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Habilidade", b =>
                {
                    b.Navigation("Profissionais");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Habilidades");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Vaga", b =>
                {
                    b.Navigation("Habilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
